### ISSUE TITLE
Crew can disband Units

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#1]
Crew can disband Unit by selecting the Unit in Map view, then selecting "Oppløs" in the unit view. You have to be logged in with the role "Crew".

**Comment by kengu** [comment]
Fixed in 0.1.1+51

**Comment by kengu** [comment]
@Anders55 - is this fixed? Can you close?

**Comment by Anders55** [comment]
Tested, confirming the issue is fixed.
