### ISSUE TITLE
Map view changes to "Topographic" when distance measure-mode is turned on/off

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#2]
When I turn on/off distance measure, the map always go to "Topographic", regardless if I was in "topographic" or another map view ("aerial", "hybrid", "topographic HD"). But once I have turned on distance measure-mode I can change between the different map views.

**Comment by kengu** [comment]
Fixed in 0.1.1+51

**Comment by kengu** [comment]
Fixed in 0.1.1+51

**Comment by kengu** [comment]
@Anders55 - is this fixed? Can you close?

**Comment by Anders55** [comment]
Tested, confirming the issue is fixed.
