### ISSUE TITLE
Show list of entries when searching

### ISSUE THREAD

**Issue by svenbruun** [DISCOOS/sarsys-app#27]
View a list of suggestions when searching. Searching for an address / location will currently not show a list of entries, it just displays and selects one. For example, when searching Kristiansand it should show both the city and the street in Oslo that starts with the same name.

**Comment by svenbruun** [comment]
Old comment from Kenneth: Yes, I've seen it. Don't quite know why the service didn't produce more results. It's Google Geocoding api. Haven't prioritized this yet. Is support in place for suggestions, but Google returns only one response. Possibly I switch to Entur's open geocoding api. It is very good for Norwegian conditions. https://developer.entur.org/pages-geocoder-intro

**Comment by kengu** [comment]
Selected for development, scheduled for 0.1.1+65

**Comment by kengu** [comment]
Will only show all items after enter is pressed. This is the same for all searches in SarSys. Will change to "autocomplete" later.
