### ISSUE TITLE
The mission leader/crew role does not change if the user has not logged off.

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#3]
During startup the app will check if you are logged inn, if you are already logged in (exiting the app without logging out) you will keep your role (mission leader/crew) regardless of what you just selected in the startup setup in your upcoming session. It will bypass the login form.

Next time you start the app you will be forced to login regardless of having logged out or not, and you will get the correct role set.

If you log out before you exit the app after have selected that you want the "startup setup" to be shown, you will get the login form after selecting role, and the role will be active immediately.

-----	
So the "issue" will be solved by resetting the "logged-in-status" when selecting role in the startup setup.

**Comment by kengu** [comment]
Fixed in 0.1.1+51

**Comment by kengu** [comment]
@Anders55 - is this fixed? Can you close?

**Comment by Anders55** [comment]
Tested, confirming the issue is fixed.
