### ISSUE TITLE
Error message when exiting Personnel/Device/Unit View

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#33]
If I zoom out and select an area with multiple Personnel, Devices or Unit, then select one of them for the pop-up list, I will get an error message if I try to exit the corresponding Personnel/Device/Unit View using the "X" in the top-right corner.

I will then get the "type 'Track' is not a subtype of type 'List<Point>'" Error message.

**Comment by kengu** [comment]
Related to #34
