### ISSUE TITLE
Can't search for Personell in Personell List

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#39]
Using build 64.

When I go to Press the search icon, the result list only show the 3 different "Status", not names. I can narrow the list by typing letters. If I choose one of the "Status", I'm send back to a Personell List, filtered for the selected "Status".

This does not add any value, as I achieve the same filtering by selecting the "Filter" icon in Personell List, and then choose what "Status" I want to see. The Search function should instead work on attributes like name, phone number, association/department etc.

**Comment by kengu** [comment]
This is the normal "suggestion" list on Android. It should not show any results, only suggested or previous searches. If you search for a name the list for matching personnnel is shown. Closing.
