### ISSUE TITLE
I can add the same Personnel to multiple Units

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#42]
If I go to Unit List, select a Unit and press "Change" I can look up Personnel and add them to the Unit. Once I start entering character a search result list shows up and I can select a Personnel.

This result list includes Personnel that is already connected with a unit, and allows me to connect a person who already is connected to one (or more) Unit to another Unit. Nothing stops me from connecting the same Personnel to all teams in the Incident.

The result list should filter away the name of those Personnel who already is connected to a Unit, to make impossible to connect the same Personnel to multiple Unit at the same time. If a Personnel is going to change Unit, they should first disconnect from the Unit the Personnel is currently connected to.

**Comment by svenbruun** [comment]
I think the name should be shown, but maybe in another color or with a text, to indicate that is already in another Unit, if this is not allowed. This gives the user an explanation to why the Personnel is not possible to add.

**Comment by Anders55** [comment]
> I think the name should be shown, but maybe in another color or with a text, to indicate that is already in another Unit, if this is not allowed. This gives the user an explanation to why the Personnel is not possible to add.

Not sure if I agree with myself on this one. Removing Personnel that are already in another unit will make it easier to get an overview of available Personell and faster to add them. To get an explanation of why a Personnel is not available, go to the Personnel list. But I still like the thought of getting a explanation of why the Personnel is not available.

**Comment by kengu** [comment]
Showing already added members is not supported. Adding filtering.
