### ISSUE TITLE
Selecting a predefined Unit creates a crash

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#49]
STR:
1. Predefine a team to be created in a new Incident by using Settings:
![Screenshot_2019-11-13-23-11-01](https://user-images.githubusercontent.com/25819162/68961384-90aced00-07d2-11ea-9e0a-2509edc00cbd.png)

2. Start a new Incident, and go to Unit List
![Screenshot_2019-11-13-23-00-43](https://user-images.githubusercontent.com/25819162/68808505-2b3dec80-066a-11ea-9134-17f6080cd5f7.png)

3. Select the predefined Unit, crash occurs:
![Screenshot_2019-11-13-23-00-48](https://user-images.githubusercontent.com/25819162/68808625-6cce9780-066a-11ea-9066-5b45901e97a0.png)

**Comment by kengu** [comment]
Same as #53.
