### ISSUE TITLE
When I try to add a Personnel to new Incident, the app crash

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#53]
STR:
1. Create a new Incident
2. Go to the Personnel List (empty)
3. Press "+" to add a new Personnel
4. Type First/Last Name and press Create
5. The app will crash:
![Screenshot_2019-11-15-22-19-40](https://user-images.githubusercontent.com/25819162/68976687-a92efe80-07f6-11ea-9d51-2107f437b945.png)

My suspicion is that it is not the creation if the Personnel that creates the crash, but the "Personnel List"-view. I can tap out the error message (tapping "x" many many times), and then add the Personnel to a Unit.

**Comment by kengu** [comment]
One or more Units must also be created for this error to occur
