### ISSUE TITLE
App crash after deleting map cache when offline

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#62]
STR:

1. Start SarSys
2. Turn of Internet connections (WiFi, 4G etc.)
3. Go to "Settings" -> and Tap "Map" under "Setup"
4. Press the trash can to the right of "Delete Map Cache"
![Screenshot_20191120-180727](https://user-images.githubusercontent.com/25819162/69260803-bebe7280-0bc0-11ea-8504-8647bde1fb02.jpg)
5. Press the "back arrow" to the left of "Map Setup" on top of the screen
6. An error message shows:
![Screenshot_20191120-180159](https://user-images.githubusercontent.com/25819162/69260895-e57ca900-0bc0-11ea-8e4e-6ec626c9583b.jpg)

If do the same procedure except step 2 (keep the phone online), the error message does not occur.

**Comment by kengu** [comment]
Fixed by #66
