### ISSUE TITLE
App crash on first startup after deleting storage

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#63]
STR:
1. Close SarSys
2. Go to Settings -> App Manager -> SarSys
3. Select "Storage" and then "Clear Data"
4. Start SarSys
5. Select Role, and enter credentials at the login screen and press "Login"
6. After pressing "Login", the app crash:
![Screenshot_2019-11-20-18-27-17](https://user-images.githubusercontent.com/25819162/69262500-dd723880-0bc3-11ea-9f8d-43c519916416.png)

7. Close SarSys, start again and it works like expected.

**Comment by kengu** [comment]
Fixed by #66
