### ISSUE TITLE
Crash when entering location of a new Incident

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#65]
STR:
1. Start SarSys

2. Create new Incident

3. Go to Location and Set IPP (press the map icon)

4. The following error occurs
![Screenshot_20191120-185903](https://user-images.githubusercontent.com/25819162/69266339-47421080-0bcb-11ea-98d3-287d9f83512c.jpg)

5. Tapping multiple times on the "Send"-icon top right of the error message gets you further, and you will see that the location has been registered:
![Screenshot_20191120-190244](https://user-images.githubusercontent.com/25819162/69266454-78badc00-0bcb-11ea-8577-8756e258ddf4.jpg)

6. Finish registering the incident, and start registering another new incident. This time you will not get an error message when you tap the map icon. But you will see that the IPP and Meetup from the previous entered Incident is still visible in the map.

**Comment by kengu** [comment]
The problem with POIs from previous active incident is not related to the bug reported here
