### ISSUE TITLE
Keyboard covers search results in Map view

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#7]
If I search for "Lag" I will get about 15 search results. When scrolling down on the result list, the last 4 search results are covered by the keyboard and therefore not visible.

Though, If i search for "Lag 1111" which does not exist, the keyboard disappears, "Lag 1111 not found" is shown on the bottom of the screen, and I can then see all search results.

**Comment by kengu** [comment]
Added limit of 10 results for now. Will redesign search i map using the same look and feel like other searches.
