### ISSUE TITLE
Logout trigger 

### ISSUE THREAD

**Issue by Anders55** [DISCOOS/sarsys-app#87]
STR:
1. Log in to SARSys
2. From burger meny, select "Log off" at the bottom

Might be "Write" happening after logoff, as it is occurs asynchronous.

Referring to:
[https://sentry.io/organizations/discoos/issues/1876958445/?project=1523681&referrer=slack](url)

![logoff](https://user-images.githubusercontent.com/25819162/92223839-5287d380-eea1-11ea-9295-8301b05b4439.png)

**Comment by kengu** [comment]
Fixed, closing
